# Host list
# "name" is mandatory and will be used as target to connect
# "title" will be displayed as "human name" instead of "name" if specified
# All defaults values can be overriden per host basis
hosts:
  - name: "152.67.91.151"
    title: MAIN HTTPS
    port: 443
    use: ncat
  - name: "152.67.91.151"
    title: MAIN HTTP
    port: 80
    use: ncat
  - name: "152.67.91.74"
    title: SERVER 1 HTTPS
    port: 443
    use: ncat
  - name: "152.67.91.74"
    title: SERVER 1 HTTP
    port: 80
    use: ncat
  - name: "152.67.89.145"
    title: SERVER 2 HTTPS
    port: 443
    use: ncat
  - name: "152.67.89.145"
    title: SERVER 2 HTTP
    port: 80
    use: ncat
    
# Site configuration
site:
  # Title
  title: Downtime
  # Favicon / logo
  favicon: https://simon.lecoq.io/src/icon.png
  # Refresh rate of status images for client
  refresh_rate_sec: 120

# Default values
defaults:
  # Default command to use
  # Supported values are :
  # - "curl"   [supports both uptime and response time, but only for HTTP/S requests]
  # - "ncat"   [supports both uptime and response time]
  # - "telnet" [supports only uptime]
  use: ncat
  # Default timeout
  timeout: 30
  # Default port
  port: 443
  # Default number of ms before considering that host have latency problems
  status_slow_ms: 30000
